apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tic-tac-toe
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/tic-tac-toe:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "file:/app/prisma/data/prod.db"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        volumeMounts:
        - name: sqlite-data
          mountPath: /app/prisma/data
      volumes:
      - name: sqlite-data
        emptyDir: {}
      timeoutSeconds: 300